// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXPqbtIQt3zOUxAoSsQX7bfnS-yS7KXU',
    appId: '1:768496068145:web:d48ec0712a90f363a91710',
    messagingSenderId: '768496068145',
    projectId: 'app-gaveta',
    authDomain: 'app-gaveta.firebaseapp.com',
    databaseURL: 'https://app-gaveta-default-rtdb.firebaseio.com',
    storageBucket: 'app-gaveta.appspot.com',
    measurementId: 'G-FVPPXBH5JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5EY65o8SiBSAh0il2CcfrrL-O3xotUqY',
    appId: '1:768496068145:android:14105ef0a9c269bca91710',
    messagingSenderId: '768496068145',
    projectId: 'app-gaveta',
    databaseURL: 'https://app-gaveta-default-rtdb.firebaseio.com',
    storageBucket: 'app-gaveta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaV_gKD7yjeDRVzSnB3rWzQhW38W482BI',
    appId: '1:768496068145:ios:7cf9de865e377002a91710',
    messagingSenderId: '768496068145',
    projectId: 'app-gaveta',
    databaseURL: 'https://app-gaveta-default-rtdb.firebaseio.com',
    storageBucket: 'app-gaveta.appspot.com',
    iosBundleId: 'br.com.gaveta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaV_gKD7yjeDRVzSnB3rWzQhW38W482BI',
    appId: '1:768496068145:ios:7cf9de865e377002a91710',
    messagingSenderId: '768496068145',
    projectId: 'app-gaveta',
    databaseURL: 'https://app-gaveta-default-rtdb.firebaseio.com',
    storageBucket: 'app-gaveta.appspot.com',
    iosBundleId: 'br.com.gaveta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXPqbtIQt3zOUxAoSsQX7bfnS-yS7KXU',
    appId: '1:768496068145:web:93016a14a3a17f37a91710',
    messagingSenderId: '768496068145',
    projectId: 'app-gaveta',
    authDomain: 'app-gaveta.firebaseapp.com',
    databaseURL: 'https://app-gaveta-default-rtdb.firebaseio.com',
    storageBucket: 'app-gaveta.appspot.com',
    measurementId: 'G-DW91PL6VPM',
  );
}
